import { PalInfo } from "../types/pal";

export const palData: PalInfo[] = [
  {
    id: "1",
    name: "도로롱",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "2",
    name: "까부냥",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "3",
    name: "꼬꼬닭",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "4",
    name: "큐룰리스",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 1,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "5",
    name: "파이호",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "6",
    name: "청부리",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "7",
    name: "번개냥",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 1,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "번개",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "8",
    name: "몽지",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "9",
    name: "불꽃밤비",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "10",
    name: "펭키",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: "얼음",
    rarity: 1,
  },
  {
    id: "11",
    name: "펭킹",
    emitFlame: 0,
    watering: 2,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 2,
    productMedicine: 0,
    cool: 2,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: "얼음",
    rarity: 6,
  },
  {
    id: "12",
    name: "찌릿도치",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 1,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "번개",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "12B",
    name: "코치도치",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "13",
    name: "초롱이",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: "땅",
    rarity: 1,
  },
  {
    id: "13B",
    name: "Gumoss (Special)",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "",
    type2: undefined,
    rarity: 10,
  },
  {
    id: "14",
    name: "미호",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "15",
    name: "아테노울",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "16",
    name: "차코리",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "17",
    name: "뚱코알라",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "18",
    name: "밀피",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "19",
    name: "몽마둥이",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "20",
    name: "돌진돼지",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "21",
    name: "루나티",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "22",
    name: "두더비",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "23",
    name: "고스문",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "24",
    name: "냐옹테트",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "24B",
    name: "칠테트",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "25",
    name: "루미카이트",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "26",
    name: "다크울프",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "27",
    name: "알록새",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "28",
    name: "토푸리",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "29",
    name: "밀카우",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "30",
    name: "가시공주",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 2,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "31",
    name: "샤키드",
    emitFlame: 0,
    watering: 2,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "31B",
    name: "샤맨더",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "32",
    name: "건다리",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: true,
    type1: "땅",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "32B",
    name: "유령건다리",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 2,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "33",
    name: "초판다",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "풀",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "33B",
    name: "썬더판다",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 2,
    handCraft: 2,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "34",
    name: "캔디쉽",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "35",
    name: "베리고트",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "36",
    name: "멜파카",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 1,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "37",
    name: "신령사슴",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "37B",
    name: "산령사슴",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "땅",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "38",
    name: "나이트윙",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "39",
    name: "핑토",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "40",
    name: "헬고트",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: "어둠",
    rarity: 4,
  },
  {
    id: "40B",
    name: "아비스고트",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "41",
    name: "귀요비",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "42",
    name: "불페르노",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "43",
    name: "도도롱",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "44",
    name: "마스크로우",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "45",
    name: "도마맨",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "45B",
    name: "칠리자드",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "46",
    name: "달서니",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "47",
    name: "질풍수리",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "48",
    name: "로빈몽",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 2,
    collection: 2,
    deforest: 1,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "48B",
    name: "산도로",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 2,
    deforest: 1,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: "땅",
    rarity: 6,
  },
  {
    id: "49",
    name: "고릴레이지",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "50",
    name: "비나이트",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 1,
    mining: 0,
    productMedicine: 1,
    cool: 0,
    transport: 2,
    monsterFarm: 1,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "51",
    name: "퀸비나",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 2,
    collection: 2,
    deforest: 1,
    mining: 0,
    productMedicine: 2,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "52",
    name: "소름냥이",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "53",
    name: "모프링",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "54",
    name: "모프킹",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 2,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "55",
    name: "베비뇽",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 1,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: "용",
    rarity: 4,
  },
  {
    id: "56",
    name: "썬더콘",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 2,
    handCraft: 0,
    collection: 0,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "57",
    name: "빙호",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 2,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "58",
    name: "파이린",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "58B",
    name: "사라블랙",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 1,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: "어둠",
    rarity: 7,
  },
  {
    id: "59",
    name: "마호",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 2,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "60",
    name: "썬도그",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 2,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "61",
    name: "불이리",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "62",
    name: "썬더 키드",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 1,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "번개",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "63",
    name: "루나리스",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 3,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "64",
    name: "플로라디노",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "풀",
    type2: "용",
    rarity: 6,
  },
  {
    id: "64B",
    name: "찌르르디노",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 2,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: "용",
    rarity: 7,
  },
  {
    id: "65",
    name: "씨무기",
    emitFlame: 0,
    watering: 2,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: undefined,
    rarity: 4,
  },
  {
    id: "65B",
    name: "스너펜트",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "땅",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "66",
    name: "마레이스",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 1,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "67",
    name: "드릴북이",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 3,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "68",
    name: "냥뱃",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 2,
    deforest: 0,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "69",
    name: "핑크뇽",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 1,
    productMedicine: 2,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "무",
    type2: undefined,
    rarity: 5,
  },
  {
    id: "70",
    name: "라비",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 1,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "71",
    name: "버드래곤",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: "어둠",
    rarity: 4,
  },
  {
    id: "71B",
    name: "시로카바네",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 2,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: "어둠",
    rarity: 5,
  },
  {
    id: "72",
    name: "불무사",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 1,
    deforest: 3,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "73",
    name: "라이버드",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 2,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "74",
    name: "적토조",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "75",
    name: "캐티메이지",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 2,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "76",
    name: "마호",
    emitFlame: 2,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 3,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "불",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "77",
    name: "초토리",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 3,
    collection: 3,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "78",
    name: "비오레타",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 2,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 3,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "79",
    name: "실키누",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 2,
    cool: 2,
    transport: 0,
    monsterFarm: 1,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "80",
    name: "실피아",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "용",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "80B",
    name: "실티아",
    emitFlame: 0,
    watering: 3,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "용",
    type2: "물",
    rarity: 8,
  },
  {
    id: "81",
    name: "켈시",
    emitFlame: 0,
    watering: 1,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "물",
    type2: undefined,
    rarity: 1,
  },
  {
    id: "81B",
    name: "마그피스",
    emitFlame: 1,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "",
    type2: undefined,
    rarity: 2,
  },
  {
    id: "82",
    name: "아주리비",
    emitFlame: 0,
    watering: 3,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: "용",
    rarity: 7,
  },
  {
    id: "83",
    name: "백랑이",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 3,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "얼음",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "84",
    name: "만티파이어",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "84B",
    name: "시니에노",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: "어둠",
    rarity: 8,
  },
  {
    id: "85",
    name: "헤로롱",
    emitFlame: 0,
    watering: 2,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: "용",
    rarity: 8,
  },
  {
    id: "85B",
    name: "핑피롱",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 3,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: "용",
    rarity: 9,
  },
  {
    id: "86",
    name: "라브라돈",
    emitFlame: 0,
    watering: 0,
    seeding: 3,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "풀",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "86B",
    name: "스프라돈",
    emitFlame: 0,
    watering: 3,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: "풀",
    rarity: 8,
  },
  {
    id: "87",
    name: "플로리나",
    emitFlame: 0,
    watering: 0,
    seeding: 3,
    generateElectricity: 0,
    handCraft: 2,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 2,
    cool: 0,
    transport: 1,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "88",
    name: "볼카노",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 3,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: "땅",
    rarity: 6,
  },
  {
    id: "88B",
    name: "프로스카노",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 3,
    productMedicine: 0,
    cool: 3,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: "땅",
    rarity: 7,
  },
  {
    id: "89",
    name: "킹파카",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "89B",
    name: "블루파카",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 3,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "90",
    name: "그린모스",
    emitFlame: 0,
    watering: 0,
    seeding: 2,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "90B",
    name: "블리자모스",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 2,
    productMedicine: 0,
    cool: 2,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "91",
    name: "움포",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 3,
    mining: 0,
    productMedicine: 0,
    cool: 2,
    transport: 4,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "91B",
    name: "트로피티",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 2,
    collection: 0,
    deforest: 3,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 4,
    monsterFarm: 0,
    ridable: true,
    type1: "풀",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "92",
    name: "장수벌레",
    emitFlame: 0,
    watering: 0,
    seeding: 1,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 3,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: "땅",
    rarity: 8,
  },
  {
    id: "93",
    name: "윈드디어",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 3,
  },
  {
    id: "94",
    name: "블러드캐티",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 3,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 6,
  },
  {
    id: "95",
    name: "페스키",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 2,
    deforest: 0,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "용",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "96",
    name: "마그마 카이저",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 4,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "97",
    name: "헬가루다",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 7,
  },
  {
    id: "98",
    name: "라바드래곤",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 1,
    collection: 0,
    deforest: 0,
    mining: 4,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "모름",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "99",
    name: "데스 스팅",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 3,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: "어둠",
    rarity: 9,
  },
  {
    id: "100",
    name: "아누비스",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 4,
    collection: 0,
    deforest: 0,
    mining: 3,
    productMedicine: 0,
    cool: 0,
    transport: 2,
    monsterFarm: 0,
    ridable: false,
    type1: "땅",
    type2: undefined,
    rarity: 10,
  },
  {
    id: "101",
    name: "레비드라",
    emitFlame: 0,
    watering: 4,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: "용",
    rarity: 8,
  },
  {
    id: "101B",
    name: "아그니드라",
    emitFlame: 4,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "102",
    name: "주작",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "102B",
    name: "시바",
    emitFlame: 0,
    watering: 3,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "물",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "103",
    name: "일렉판다",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 3,
    handCraft: 2,
    collection: 0,
    deforest: 2,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "번개",
    type2: undefined,
    rarity: 8,
  },
  {
    id: "104",
    name: "릴린",
    emitFlame: 0,
    watering: 0,
    seeding: 4,
    generateElectricity: 0,
    handCraft: 3,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 3,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "풀",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "104B",
    name: "루나퀸",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 3,
    collection: 2,
    deforest: 0,
    mining: 0,
    productMedicine: 3,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: false,
    type1: "어둠",
    type2: undefined,
    rarity: 10,
  },
  {
    id: "105",
    name: "호루스",
    emitFlame: 3,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: true,
    type1: "불",
    type2: undefined,
    rarity: 9,
  },
  {
    id: "106",
    name: "전룡맨",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 4,
    handCraft: 2,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 3,
    monsterFarm: 0,
    ridable: false,
    type1: "번개",
    type2: "용",
    rarity: 9,
  },
  {
    id: "107",
    name: "제노그리프",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 1,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 10,
  },
  {
    id: "108",
    name: "팔라디우스",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "무",
    type2: undefined,
    rarity: 20,
  },
  {
    id: "109",
    name: "켄타나이트",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 2,
    mining: 2,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 20,
  },
  {
    id: "110",
    name: "빙천마",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 0,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 4,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "얼음",
    type2: undefined,
    rarity: 20,
  },
  {
    id: "110B",
    name: "그레이섀도우",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 4,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "어둠",
    type2: undefined,
    rarity: 20,
  },
  {
    id: "111",
    name: "제트래곤",
    emitFlame: 0,
    watering: 0,
    seeding: 0,
    generateElectricity: 0,
    handCraft: 0,
    collection: 3,
    deforest: 0,
    mining: 0,
    productMedicine: 0,
    cool: 0,
    transport: 0,
    monsterFarm: 0,
    ridable: true,
    type1: "용",
    type2: undefined,
    rarity: 20,
  },
];
