import { passives } from "./passives";
export type ActualPal = {
  name: string;
  gender: string;
  passives: string[];
};

export const sampleData = [
  { name: "번개냥", gender: "여", passives: ["밤의 장막"] },
  { name: "파이호", gender: "남", passives: ["부실한 뼈", "사나움"] },
  { name: "다크울프", gender: "남", passives: ["긍정적인 사고"] },
  { name: "베비뇽", gender: "남", passives: [] },
  { name: "몽지", gender: "남", passives: ["성실함"] },
  { name: "도도롱", gender: "여", passives: ["일 중독"] },
  { name: "냥뱃", gender: "여", passives: ["사나움"] },
  {
    name: "파이호",
    gender: "여",
    passives: ["달리기 왕", "용 학살자", "일 노예"],
  },
  { name: "차코리", gender: "여", passives: ["장인 기질"] },
  { name: "핑토", gender: "남", passives: ["일 노예"] },
  { name: "꼬꼬닭", gender: "남", passives: ["일 중독"] },
  { name: "도로롱", gender: "여", passives: ["장인 기질"] },
  { name: "플로리나", gender: "남", passives: [] },
  { name: "미호", gender: "여", passives: ["식습관의 달인"] },
  { name: "신령사슴", gender: "남", passives: ["철옹성의 책사"] },
  { name: "냥뱃", gender: "여", passives: ["성실함", "무의 경지"] },
  { name: "도로롱", gender: "남", passives: ["소식"] },
  { name: "도로롱", gender: "여", passives: ["콘덴서"] },
  { name: "도로롱", gender: "남", passives: ["철옹성의 책사"] },
  { name: "도로롱", gender: "남", passives: ["용감"] },
  { name: "꼬꼬닭", gender: "여", passives: ["용감"] },
  { name: "꼬꼬닭", gender: "남", passives: ["냉혈"] },
  {
    name: "꼬꼬닭",
    gender: "여",
    passives: ["광산 관리자", "식습관의 달인"],
  },
  { name: "꼬꼬닭", gender: "여", passives: ["대지의 힘"] },
  { name: "꼬꼬닭", gender: "남", passives: ["성실함"] },
  { name: "꼬꼬닭", gender: "남", passives: ["콘덴서"] },
  { name: "큐룰리스", gender: "여", passives: ["불량배"] },
  { name: "큐룰리스", gender: "남", passives: ["철옹성의 책사"] },
  { name: "큐룰리스", gender: "여", passives: ["방수 가공"] },
  {
    name: "큐룰리스",
    gender: "남",
    passives: ["운동 바보", "장인 기질", "억센 육체"],
  },
  { name: "큐룰리스", gender: "여", passives: ["방초 효과"] },
  { name: "큐룰리스", gender: "여", passives: ["마조히스트"] },
  { name: "큐룰리스", gender: "남", passives: ["신속", "무의 경지"] },
  { name: "파이호", gender: "남", passives: ["난폭함"] },
  { name: "파이호", gender: "여", passives: ["물놀이 선호"] },
  { name: "파이호", gender: "남", passives: ["초목의 향기"] },
  { name: "파이호", gender: "여", passives: ["철옹성의 책사"] },
  { name: "파이호", gender: "여", passives: ["어브노멀"] },
  { name: "파이호", gender: "여", passives: ["마조히스트"] },
  { name: "파이호", gender: "여", passives: ["신속"] },
  { name: "파이호", gender: "남", passives: ["광산 관리자"] },
  { name: "파이호", gender: "남", passives: ["방수 가공"] },
  { name: "파이호", gender: "여", passives: ["방수 가공"] },
  { name: "파이호", gender: "남", passives: ["긍정적인 사고"] },
  {
    name: "파이호",
    gender: "남",
    passives: ["일 중독", "사디스트", "대지의 힘"],
  },
  { name: "파이호", gender: "여", passives: ["돌격 지휘자"] },
  { name: "청부리", gender: "남", passives: ["마조히스트"] },
  { name: "청부리", gender: "여", passives: ["내진 구조"] },
  { name: "청부리", gender: "여", passives: ["희귀", "돌격 지휘자"] },
  { name: "청부리", gender: "남", passives: ["긍정적인 사고"] },
  { name: "번개냥", gender: "남", passives: ["억센 육체"] },
  {
    name: "번개냥",
    gender: "여",
    passives: ["장인 기질", "무의 경지", "철옹성의 책사"],
  },
  { name: "몽지", gender: "남", passives: ["불량배"] },
  { name: "몽지", gender: "여", passives: ["고온 체질"] },
  { name: "몽지", gender: "여", passives: ["일 중독"] },
  { name: "몽지", gender: "여", passives: ["내진 구조"] },
  { name: "몽지", gender: "남", passives: ["방초 효과"] },
  { name: "불꽃밤비", gender: "여", passives: ["철옹성의 책사"] },
  { name: "불꽃밤비", gender: "여", passives: ["난폭함"] },
  { name: "불꽃밤비", gender: "여", passives: ["밝은 성격"] },
  { name: "불꽃밤비", gender: "남", passives: ["신속"] },
  {
    name: "불꽃밤비",
    gender: "남",
    passives: ["약한 맷집", "밝은 성격", "냉혈"],
  },
  { name: "펭키", gender: "남", passives: ["내진 구조"] },
  { name: "펭키", gender: "여", passives: ["방초 효과"] },
  { name: "펭키", gender: "여", passives: ["어브노멀"] },
  { name: "펭키", gender: "남", passives: ["일 중독"] },
  {
    name: "찌릿도치",
    gender: "남",
    passives: ["절연체", "약한 맷집", "성실함"],
  },
  { name: "찌릿도치", gender: "여", passives: ["일 중독"] },
  { name: "초롱이", gender: "여", passives: ["달리기 왕"] },
  { name: "초롱이", gender: "남", passives: ["불놀이 선호"] },
  { name: "초롱이", gender: "남", passives: ["자만심"] },
  { name: "미호", gender: "남", passives: ["방초 효과"] },
  { name: "미호", gender: "여", passives: ["동기 부여", "무의 경지"] },
  { name: "아테노울", gender: "여", passives: ["억센 육체"] },
  { name: "아테노울", gender: "여", passives: ["무의 경지"] },
  { name: "아테노울", gender: "여", passives: ["방초 효과"] },
  { name: "차코리", gender: "여", passives: ["운동 바보"] },
  { name: "차코리", gender: "남", passives: ["난폭함"] },
  { name: "뚱코알라", gender: "남", passives: ["신속"] },
  { name: "뚱코알라", gender: "여", passives: ["물놀이 선호"] },
  { name: "뚱코알라", gender: "여", passives: ["소식"] },
  { name: "뚱코알라", gender: "남", passives: ["용 학살자"] },
  { name: "뚱코알라", gender: "남", passives: ["벌목 관리자"] },
  { name: "뚱코알라", gender: "여", passives: ["밤의 장막"] },
  {
    name: "뚱코알라",
    gender: "여",
    passives: ["동기 부여", "내진 구조", "일광욕 선호"],
  },
  { name: "뚱코알라", gender: "남", passives: ["용 학살자"] },
  { name: "밀피", gender: "여", passives: ["사나움"] },
  { name: "밀피", gender: "남", passives: ["달리기 왕"] },
  {
    name: "밀피",
    gender: "남",
    passives: ["용 학살자", "식습관의 달인", "재빠름"],
  },
  { name: "밀피", gender: "남", passives: ["밤의 장막"] },
  { name: "밀피", gender: "여", passives: ["불놀이 선호"] },
  {
    name: "밀피",
    gender: "여",
    passives: ["정신 불안정", "달리기 왕"],
  },
  { name: "몽마둥이", gender: "남", passives: ["운동 바보"] },
  { name: "몽마둥이", gender: "남", passives: ["장인 기질"] },
  {
    name: "몽마둥이",
    gender: "남",
    passives: ["광산 관리자", "긍정적인 사고"],
  },
  { name: "몽마둥이", gender: "남", passives: ["성실함"] },
  { name: "몽마둥이", gender: "여", passives: ["일 노예"] },
  { name: "돌진돼지", gender: "남", passives: ["돌격 지휘자"] },
  {
    name: "돌진돼지",
    gender: "여",
    passives: ["무의 경지", "난폭함", "철옹성의 책사"],
  },
  { name: "돌진돼지", gender: "여", passives: ["동기 부여"] },
  { name: "돌진돼지", gender: "남", passives: ["용감"] },
  {
    name: "돌진돼지",
    gender: "남",
    passives: ["성실함", "밤의 장막", "냉혈"],
  },
  { name: "돌진돼지", gender: "남", passives: ["콘덴서"] },
  { name: "돌진돼지", gender: "남", passives: ["내진 구조"] },
  {
    name: "루나티",
    gender: "여",
    passives: ["어브노멀", "사디스트", "냉혈", "단단한 피부"],
  },
  { name: "두더비", gender: "여", passives: ["초목의 향기"] },
  { name: "두더비", gender: "여", passives: ["성실함"] },
  { name: "두더비", gender: "여", passives: ["장인 기질", "무사주의"] },
  { name: "고스문", gender: "여", passives: ["밝은 성격"] },
  { name: "냐옹테트", gender: "여", passives: ["자만심"] },
  { name: "루미카이트", gender: "여", passives: ["성실함"] },
  {
    name: "루미카이트",
    gender: "남",
    passives: ["불놀이 선호", "긍정적인 사고", "장인 기질"],
  },
  { name: "루미카이트", gender: "남", passives: ["물놀이 선호"] },
  { name: "루미카이트", gender: "남", passives: ["재빠름"] },
  { name: "다크울프", gender: "여", passives: ["소식"] },
  { name: "다크울프", gender: "남", passives: ["사디스트"] },
  { name: "가스공주", gender: "남", passives: [] },
  { name: "건다리", gender: "남", passives: ["블랙홀 위장"] },
  { name: "베리고트", gender: "남", passives: ["달리기 왕"] },
  { name: "베리고트", gender: "남", passives: ["초목의 향기"] },
  { name: "베리고트", gender: "남", passives: ["불량배"] },
  { name: "베리고트", gender: "남", passives: ["콘덴서"] },
  { name: "멜파카", gender: "여", passives: ["무의 경지"] },
  { name: "멜파카", gender: "여", passives: ["냉혈"] },
  { name: "멜파카", gender: "여", passives: ["용감", "사나움"] },
  { name: "신령사슴", gender: "여", passives: ["마조히스트"] },
  { name: "신령사슴", gender: "남", passives: ["신속"] },
  { name: "나이트윙", gender: "남", passives: ["동기 부여"] },
  { name: "핑토", gender: "여", passives: ["어브노멀"] },
  { name: "핑토", gender: "여", passives: ["철옹성의 책사"] },
  { name: "핑토", gender: "여", passives: ["성실함"] },
  { name: "핑토", gender: "여", passives: ["달리기 왕"] },
  {
    name: "핑토",
    gender: "남",
    passives: ["자만심", "성실함", "냉혈", "돌격 지휘자"],
  },
  { name: "핑토", gender: "남", passives: ["불량배"] },
  { name: "핑토", gender: "여", passives: ["초목의 향기"] },
  { name: "귀요비", gender: "남", passives: ["물놀이 선호"] },
  { name: "모프링", gender: "여", passives: ["단단한 피부"] },
  { name: "모프링", gender: "남", passives: ["일광욕 선호"] },
  { name: "모프링", gender: "남", passives: ["초목의 향기"] },
  { name: "모프링", gender: "여", passives: ["신속"] },
  { name: "모프킹", gender: "여", passives: [] },
  { name: "베비뇽", gender: "남", passives: [] },
  { name: "플로라디노", gender: "남", passives: ["벌목 관리자"] },
  { name: "플로라디노", gender: "여", passives: ["장인 기질"] },
  { name: "라비", gender: "여", passives: [] },
  { name: "켈시", gender: "남", passives: ["난폭함"] },
  {
    name: "큐룰리스",
    gender: "여",
    passives: ["광산 관리자", "재빠름"],
  },
].map((item, index) => ({ ...item, id: index }));
